### ISSUE TITLE
HTTP Sataus code in response

### ISSUE THREAD

**Issue by samtajoshi20** [clxcommunications/sdk-xms-php#1]
I am sending the sms using following code:

$client = new Clx\Xms\Client('a************1', 'cdf6****************23');

try {
    $batchParams = new Clx\Xms\Api\MtBatchTextSmsCreate();
    $batchParams->setSender('12345');
    $batchParams->setRecipients(['987654321', '123456789', '567894321']);
    $batchParams->setBody('Hello, Samta!');
    $batchParams->setParameters(
        [
            'name' => [
                '987654321' => 'Mary',
                '123456789' => 'Joe',
                'default' => 'valued customer'
            ]
        ]
    );

    $batch = $client->createTextBatch($batchParams);
    echo "<pre>";
    print_r($batch); 
    echo('The batch was given ID ' . $batch->getBatchId() . "\n");
} catch (Exception $ex) {
    echo('Error creating batch: ' . $ex->getMessage() . "\n");
}

But the $batch is not containning any http status code in response from api.

Can you please tell me using which funciton I can get http response status code.

**Comment by rycee** [comment]
Yeah, as you noticed the batch does not include the HTTP status.

In general the HTTP status is handled by the library and is not exposed through the API, instead we use PHP exceptions for non-success HTTP status codes. In other words, if the `$batch = $client->createTextBatch($batchParams)` call succeeds then the HTTP response status was 201.

If instead you get an `UnauthorizedException` then the HTTP status code was 401, `NotFoundException` corresponds to HTTP status 404, `ErrorResponseException` is thrown for 400 and 403. Any other HTTP status code will result in a `UnexpectedResponseException` which does include the code in the exception message.

Is this sufficient for your needs?

**Comment by rycee** [comment]
Also, if 'atiun_comunicac1' and 'ca640950431147c5a0464162c54e8582' are your real credentials then please contact CLX support about changing them since they should be treated confidentially.

**Comment by samtajoshi20** [comment]
I need delivery report of sms send and store it in db. but I am not able to recieve it from api. I have set the delievery report to summary using echo $batch->getDeliveryReport();
Also the exception is also not giving any message if I updated any key or secret then it should give me UnauthorizedException. But the message in catch is blank

**Comment by rycee** [comment]
That is correct, `UnauthorizedException` does not include a message, it does include the methods `getServicePlanId()` and `getToken()` that can be used to retrieve information. I think it is a good idea to also have a message though so I'll have a look at including one in the next release.

About the delivery report I don't quite follow. Are you not getting the delivery report callbacks? Or is the `Client::fetchDeliveryReport()` method not successfully retrieving the delivery report?
